######################################################################################
# Function to compute trait richness index TOP (Fontana et al. 2015)                 
# Partially adapted from Villeger et al. 2008
# Additional comments added in by CYFC Aug 2021
#                                                                                     
# It requires R libraries 'geozoo', 'flexmix' and 'geometry'                                                              #                                                                              
# input:                                                                             
# - data frame 'traits': every row represents an individual, every column a trait
# - number of individuals must be higher than number of traits    
# - NA are not allowed                                                                         
# - ADVICE: it is generally meaningful to standardise trait values (mean=0 and sd=1)                                      
######################################################################################


##################
##  TOP index   ##
##################

library(geometry)


TOP.index <- function(traitdat){
  
  # TOP
  
  dim1 <- ncol(traitdat)
  
  #definitions: index i, area as empty vector
  
  i=0
  area<-matrix(ncol=2,nrow=nrow(traitdat))
  
  while(nrow(traitdat)>dim1){
    i=i+1
    
    # use of convhulln function
    
    # area
    area[i,2] <- convhulln(traitdat,"FA")$area
    
    # identity of vertices
    vert0<-convhulln(traitdat,"Fx TO 'vert.txt'")
    vert1<-scan("vert.txt",quiet=T)
    area[i,1] <- vert1[1] # first row is a count of convex hull vertices
    vertices <- vert1[-1] + 1 # remove the count and correct the output to give row indexes (in traitdat) for vertices
    # note by CFYC: + 1 because convexhulln/qHull by default indexes the first point as 0, and first row of trait data is at row 2.
  
    traitdat <- traitdat[-vertices,] # "peel" this layer off by removing the vertices
    area[i,1] <- length(vertices) # calculate the size of the convex hull
    
  } # keep peeling

  area<-na.omit(area)
  # Output (2 numbers): Number of points touched by areas; Sum of the areas (TOP index)
  colSums(area)
  
  # # delete the file generated by the function
  # if (file.exists('vert.txt')) {
  #   #Delete file if it exists
  #   invisible(file.remove('vert.txt'))
  # }
  
}


